version: '3.8'
services:
  web:
    image: nginx:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet
    environment:
      ENV_VAR: value

networks:
  webnet:
